### ISSUE TITLE
Library fails to detect Chrome browser

### ISSUE THREAD

**Issue by johnknoop** [daphnesmit/prntr#11]
Hi

There seems to be some code in your library that wants to use the `focus` event for Chrome and Firefox to trigger the `onPrintDialogClose` callback. The problem is that `Browser$1.isChrome()` returns `false` for me in Chrome 97.0.4692.99 (Win 11), causing it to keep listening for `mouseover`.

![image](https://user-images.githubusercontent.com/3394270/151975024-d9d20f4b-3b7c-4e61-962e-5ba9b316751d.png)

This prevents `onPrintDialogClose` from getting called.

If I set a breakpoint on line 103 in your code and overwrite the `event` variable with the value `focus` using the console, then the callback gets triggered without any need to move the mouse around.

Maybe there is a better way you can test which browser is being used? Alternatively accept a config option that lets the application tell prntr which browser is running (which in my case would be easy since I'm using the [bowser ](https://www.npmjs.com/package/bowser)library). Since this is a TS library, a discriminated union of `'Chrome' | 'Edge' | 'Firefox' | ...` would make for a neat API design that prevents mistakes.

**Comment by daphnesmit** [comment]
I will change the browser detect file to use bowser
