### ISSUE TITLE
iframe remains in DOM after print/cancel

### ISSUE THREAD

**Issue by pgmann** [daphnesmit/prntr#22]
Chrome version: 97.0.4692.99
Windows version: 21H2 (19044.1466)

As per the title, the iframe is remaining in the DOM after closing the chrome print dialog. It is only removed if I unfocus the window and refocus it.

The impact of this is bigger than you would expect, as in my Vue-Router app using browser nav to go back then forward again will reopen the print dialog as soon as the component for that route loads.

**Comment by daphnesmit** [comment]
Which version of print js are you using and can you provide a reproducable case?
After trying this with latest version and our example folder in chrome 97 on windows 10 I dont see it happening. 

also this lib is based on print-js : https://github.com/crabbly/Print.js/issues/495 
it has same issue. doing a cleanup to early might cause printing to not work at all unfortunately.

**Comment by daphnesmit** [comment]
Also feel free to make a pr to fix it.

**Comment by daphnesmit** [comment]
Perhaps this is a solution: https://github.com/crabbly/Print.js/issues/495#issuecomment-733043013

But that would need to be thoroughly browserchecked. because i saw on Edge already when you do then on mouseover hack it triggers in between opening the print window. which will cause printing to fail.

**Comment by pgmann** [comment]
It was version 2.0.8, I'd also tried the latest version of print-js too. Maybe I could just remove the iframe myself if it exists whenever my app's route changes (i.e. on page navigation)? Not ideal, but would likely work in my case.

The linked issue looks promising, unfortunately I'm not sure I'd have the time commitment to test this cross-browser - sorry!

**Comment by daphnesmit** [comment]
Hey! I added bunch of dumb version with some testing on a bug in Edge where the iframe got removed to quickly.  Maybe use the latets to be sure. In the newest in Edge there the iframe also gets removed onFocus. So you might have the same issue happening in edge or firefox.

Annoying thing is on mouseover got fired way to quicky even before the print window was opened, causing the iframe to be removed and the print dialog opening to be cancelled. 

If i have some time later this week or so I will check if one of those linked solutions works in all those different browsers. For now you could indeed maybe onPrintDialogClose or such call:
`document.getElementById('prntr').remove()`

don't know if programmatically putting focus somewhere might work aswell.

**Comment by daphnesmit** [comment]
@pgmann  I add iframeRemovalDelay: number as a config prop to prntr
