### ISSUE TITLE
Only prints first page of pdf on Safari iOS

### ISSUE THREAD

**Issue by DarrBuck** [daphnesmit/prntr#26]
When printing a pdf using Safari on an iPad it only prints the first page.

Any idea how to resolve this?

**Comment by daphnesmit** [comment]
Its not solveable unfortunately. I did make a fix for ipad, iphone or safari desktop when they dont support pdf print to open the file in a new window. so at least it loads.

**Comment by daphnesmit** [comment]
I added more incompatible browser checks
