### ISSUE TITLE
navigator is undefined

### ISSUE THREAD

**Issue by dargmuesli** [daphnesmit/prntr#30]
Looks like those navigators need to be checked for, at least for SSR:
https://github.com/daphnesmit/prntr/blob/d9b17e2529b417e4a26910eee182365565023e5b/src/utils/browser.ts#L22-L24

**Comment by daphnesmit** [comment]
Im fixing

**Comment by daphnesmit** [comment]
2.0.14 on its way now

**Comment by daphnesmit** [comment]
sorry 2.0.15

**Comment by dargmuesli** [comment]
Great, it works! Thank you.
