### ISSUE TITLE
`onPrintDialogClose` doesn't trigger in Firefox anymore

### ISSUE THREAD

**Issue by johnknoop** [daphnesmit/prntr#32]
Hi!

The latest version doesn't trigger `onPrintDialogClose` in Firefox anymore.

I tried downgrading to version `2.0.1` and that solved the problem, so the regression is in one of the later versions since then.

I'm on Windows 11.

**Comment by johnknoop** [comment]
Oh, I now saw your comment in the code (`// Ps.: Firefox will require an extra click in the document to fire the focus event.`). Any idea if this can be fixed somehow?

**Comment by daphnesmit** [comment]
I am creating new version with ff check in codes. I will post once deployed @johnknoop

**Comment by daphnesmit** [comment]
2.0.16
