### ISSUE TITLE
[Feature Request] Cancel/Print event

### ISSUE THREAD

**Issue by Maennam** [daphnesmit/prntr#37]
Hi !

Is there any possibility to get a cancel/print event ?
Maybe within the onPrintDialogClose property ?

I need to save the information that some files have been printed, i can't find any solution.

Thank your for your great work !

Regards

**Comment by daphnesmit** [comment]
onPrintDialogClose should do that already. might not work greatly in every browser because the state of programmatically open the printing window is not great these days
